services:
  backend:
    build: ./
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=ticket
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
#    volumes:
#      - db-data:/var/lib/postgresql/data1
    networks:
      - spring-postgres
    environment:
      - POSTGRES_PASSWORD=ticket123
      - POSTGRES_DB=ticket
      - POSTGRES_USER=postgres
#      - PGDATA= /var/lib/postgresql/data1
    expose:
      - 5432
    ports:
      - 5432:5432
#volumes:
#  db-data:
networks:
  spring-postgres: