services:
  backend:
    build: ./
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=ticket
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=ticket123
    networks:
      - spring-postgres
  postgres:
    image: postgres
    restart: always
    networks:
      - spring-postgres
    environment:
      - POSTGRES_PASSWORD=ticket123
      - POSTGRES_DB=ticket
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
networks:
  spring-postgres: